  ---
- hosts: [app, appdb, reverse_proxy]
  remote_user: root
  tasks:
    - name: Set authorized key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/Users/boerni/.ssh/id_rsa.pub') }}"

    - name: Ensure hostname set
      hostname: name={{ inventory_hostname }}
      when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')

    - name: Upgrade APT to the latest packages
      apt: upgrade=safe

    - name: set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin

    - name: PasswordAuthentication no
      replace:
        path: "/etc/ssh/sshd_config"
        regexp: '^#?PasswordAuthentication .*$'
        replace: "PasswordAuthentication no"

    - name: Reload sshd
      systemd:
        state: reloaded
        name: ssh

  roles:
    - role: jnv.unattended-upgrades
      unattended_remove_unused_dependencies: true
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: '03:00'
